### ISSUE TITLE
readme: does BOOT not need to be held down?

### ISSUE THREAD

**Issue by colemickens** [MatthewCroughan/visionfive-nix#4]
This documentation page seems to indicate BOOT must be pressed when applying power for the recovery sequence. This seems like it would be necessary... https://rvspace.org/en/Product/VisionFive/Technical_Documents/VisionFive_Single_Board_Computer_Quick_Start_Guide

Maybe just a small oversight in README? Or maybe readme should just link to that doc and tell users to ctrl-f for "Recovering the bootloader"?

**Comment by MatthewCroughan** [comment]
To flash the bootloader, rather than the original firmware, you do not have to hold down the BOOT button. This was part of the same confusion in #5. I explain the whole process in this Youtube video https://www.youtube.com/watch?v=cmjK8SLIx9E
