### ISSUE TITLE
flashing hangs?

### ISSUE THREAD

**Issue by colemickens** [MatthewCroughan/visionfive-nix#5]
Right after "Waiting for bootloader mode..." I plugged in power to the  board with BOOT button held down.

Then this happened. :/ Uh oh:

```
++ /nix/store/zgv13xgivl8ynv11gmc7rn1r77f8gm4r-jh7100-recover/bin/jh7100-recover -D /dev/ttyUSB0 -r /nix/store/znwpiv56ppnba07c64z260r85r5p7zr3-source -b /nix/store/l10fx61rm753vfvl2hr6rqqpvzw3r7sm
-source -d /nix/store/j2gjiyiq3m8vqah21vrzzy2ksaaayiqq-source
Waiting for bootloader mode on /dev/ttyUSB0...


(C)SiFive
Bootloader mode active

Uploading recovery binary...
load 0x18000000
        Waiting for XMODEM request[C]...
        Sending /nix/store/znwpiv56ppnba07c64z260r85r5p7zr3-source
[########################################] 100%  24081/24081 Bytes
do 0x18000000

----------Enter recovery mode----------
Updating bootloader...


Load file  ok



# do 0x18000000�H�j�ˋ�  WZ�j"�ي"՝5RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRjIIIIIIIIIIIIIII
```

**Comment by colemickens** [comment]
Huh, this doesn't quite seem to line up with the `expect` script? Are there bootrom differences? or? For example the expect script expects "DDR" at one point, but I don't see that anywhere.

And it seems to have slurped some sort of file from somewhere because there was a progress bar before it turned to "Load file ok".

**Comment by colemickens** [comment]
Uh oh, I think I confused "flash-original" and "flash-bootloader" :/

**Comment by MatthewCroughan** [comment]
Yeah, I have not yet documented flash original. But it expects to be ran from the DEBUG port at 9600 baud.

**Comment by colemickens** [comment]
Weird, I didn't have to mess with the baudrate, I guess the recovery binary does that automatically. Turns out the instructions are almost identical. I have a fork with slight changes to the README and more invasive changes that make this repo a bit easier to use from external repos. I'll try to send along some notes later or catch you on Matrix if you want to chat. Thanks again for this work! Having the u-boot flashing process wrapped in nix makes it so :man_cook: :kiss: (we need a chef's kiss emoji!)

**Comment by MatthewCroughan** [comment]
@colemickens I've messaged you on Matrix also :smile:

**Comment by MatthewCroughan** [comment]
I will fix the README to indicate the difference, so that this is less likely in the future.
